name: auto version on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  call-auto-tag:  # This is a custom job name
    uses: chandrun2989/aws_ec2-test/.github/workflows/auto-ver-tag.yaml@main
    with:
      target_branch: "main"
      version_file: "VERSION"
      changelog_file: "CHANGELOG.md"
  